2018-05-29 16:52:04,725 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:47]
2018-05-29 17:16:57,158 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:47]
2018-05-29 17:17:02,114 ERROR: Exception on /login [GET] [in c:\users\lumo\envs\flask\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\lumo\envs\flask\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lumo\envs\flask\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lumo\envs\flask\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lumo\envs\flask\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\lumo\envs\flask\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lumo\envs\flask\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Lumo\Desktop\microblog\app\routes.py", line 61, in login
    return render_template('login.html', title='Sign In', form=form)
  File "c:\users\lumo\envs\flask\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\lumo\envs\flask\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\lumo\envs\flask\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\lumo\envs\flask\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lumo\envs\flask\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Lumo\Desktop\microblog\app\templates\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Lumo\Desktop\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\lumo\envs\flask\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\lumo\envs\flask\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\lumo\envs\flask\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\lumo\envs\flask\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 26, in block "body"
    {% block scripts %}
  File "C:\Users\Lumo\Desktop\microblog\app\templates\base.html", line 5, in block "scripts"
    {{ moment.include_moment() }}
  File "c:\users\lumo\envs\flask\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'moment' is undefined
2018-05-29 17:17:34,496 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:49]
2018-05-29 21:37:08,052 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 21:38:08,593 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 21:39:34,336 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 21:40:25,868 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 21:42:25,622 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 22:10:22,130 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 22:11:02,921 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 22:11:20,752 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 22:13:03,064 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 22:14:11,801 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 22:14:26,616 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 22:14:30,850 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 22:16:17,039 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 22:18:13,246 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 22:18:32,237 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 22:18:41,530 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 22:18:52,757 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 22:19:04,688 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 22:24:34,213 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 22:26:37,813 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 22:28:57,669 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 22:29:04,061 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 22:29:32,424 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 22:30:53,398 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 22:30:56,586 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 22:31:11,269 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 22:36:47,932 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 22:42:13,200 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 22:58:44,140 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 23:19:26,390 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-05-29 23:19:48,653 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-06-02 09:46:44,320 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-06-02 09:47:12,790 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-06-02 09:47:55,104 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-06-02 09:48:06,489 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-06-02 09:48:44,162 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-06-02 09:51:21,179 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-06-02 09:54:33,572 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-06-02 09:56:03,921 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-06-02 09:57:12,749 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-06-02 09:57:28,012 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-06-02 09:57:52,950 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-06-02 09:59:07,696 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-06-02 10:00:27,677 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-06-02 10:00:45,262 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-06-02 10:01:24,678 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
2018-06-02 10:01:30,514 ERROR: Exception on /translate [POST] [in c:\users\lumo\envs\flask\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\lumo\envs\flask\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lumo\envs\flask\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lumo\envs\flask\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lumo\envs\flask\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\lumo\envs\flask\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lumo\envs\flask\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lumo\envs\flask\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Lumo\Desktop\microblog\app\routes.py", line 205, in translate_text
    request.form['dest_language'])})
  File "C:\Users\Lumo\Desktop\microblog\app\translate.py", line 15, in translate
    print (r.content.text)
AttributeError: 'bytes' object has no attribute 'text'
2018-06-02 10:03:08,156 INFO: Microblog startup [in C:\Users\Lumo\Desktop\microblog\app\__init__.py:52]
